server:
  port: 8766
spring:
  application:
    name: ConsumerUserServiceFeign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #访问http://localhost:8766/actuator/hystrix.stream能看到不断更新的监控流